### ISSUE TITLE
NotImplementedError in pytorch3d

### ISSUE THREAD

**Issue by Zevrap-81** [GAP-LAB-CUHK-SZ/REC-MV#10]
Hello, I am trying to run the large pose demo described in the readme
```
bash ./scripts/large_pose/test_large_pose_fl.sh 0 anran_tic anran_tic_self_rotated
```

but i am getting the following error related to pytorch3d. Can you help me in this regard?

```
0    surface finder start!
Traceback (most recent call last):
  File "infer_fl.py", line 260, in <module>
    colors_list,imgs_list,def1imgs_list,defVs_list, smpl_list, merge_imgs=optNet.infer_garment(garment_TmpVs,garment_Tmpfs, dataset.H, dataset.W,ratio,frame_ids,args.nColor,gts, args.rec_root)
  File "/home/engineer/networks/OptimGarmentNetwork.py", line 2965, in infer_garment
    self.registry_meshes = self.registration(fl_curve, TmpVs_list, Tmpfs_list, ratio, root)
  File "/home/engineer/networks/OptimGarmentNetwork.py", line 2442, in registration
    garment_masks = surface_finder(target_garments, device)
  File "/home/engineer/networks/OptimGarmentNetwork.py", line 2370, in surface_finder
    __, fragment=view_renderer(meshes, cameras=newcameras)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/app/pytorch3d/pytorch3d/renderer/mesh/renderer.py", line 107, in forward
    fragments = self.rasterizer(meshes_world, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/app/pytorch3d/pytorch3d/renderer/mesh/rasterizer.py", line 224, in forward
    meshes_proj = self.transform(meshes_world, **kwargs)
  File "/app/pytorch3d/pytorch3d/renderer/mesh/rasterizer.py", line 201, in transform
    to_ndc_transform = cameras.get_ndc_camera_transform(**kwargs)
  File "/app/pytorch3d/pytorch3d/renderer/cameras.py", line 280, in get_ndc_camera_transform
    if self.in_ndc():
  File "/app/pytorch3d/pytorch3d/renderer/cameras.py", line 375, in in_ndc
    raise NotImplementedError()
NotImplementedError
```

**Comment by lingtengqiu** [comment]
What is your pytorch3d version? 
In my experiment setting, I use the 0.4.0 version.

**Comment by Zevrap-81** [comment]
it is 0.7.4

**Comment by lingtengqiu** [comment]
Please change it to pytorch3d==0.4.0;
```
wget -O pytorch3d-0.4.0.zip https://github.com/facebookresearch/pytorch3d/archive/refs/tags/v0.4.0.zip
unzip pytorch3d-0.4.0.zip
cd pytorch3d-0.4.0 && python setup.py install && cd ..
```

**Comment by Zevrap-81** [comment]
I was getting errors during installation of this version. so i installed it according to the instructions on pytorch3d website

**Comment by lingtengqiu** [comment]
may be your PyTorch>1.10.2?
For latest Pytorch is not compatible with pytorch==0.4

**Comment by Zevrap-81** [comment]
for pytorch3d==0.4.0, it requires cuda10.2 but this is not supported by my gpu. what cuda version are you using?

**Comment by msverma101** [comment]
i dont see why this issue was closed?

**Comment by lingtengqiu** [comment]
> for pytorch3d==0.4.0, it requires cuda10.2 but this is not supported by my gpu. what cuda version are you using?

I use the Single RTX-3090 GPU. The Cuda version is 11.3? are you sure 10.1 requires cuda 10.2?

**Comment by Zevrap-81** [comment]
in the readme file for pytorch3d:v0.4.0 it says it supports torch:v1.7.1 latest

<describe>

```
  The core library is written in PyTorch. Several components have underlying implementation in CUDA for improved performance. A subset of these components have CPU implementations in C++/Pytorch. It is advised to use PyTorch3D with GPU support in order to use all the features.
  
      Linux or macOS or Windows
      Python 3.6, 3.7 or 3.8
      PyTorch 1.4, 1.5.0, 1.5.1, 1.6.0, 1.7.0, or 1.7.1.
      torchvision that matches the PyTorch installation. You can install them together as explained at pytorch.org to make sure of this.
      gcc & g++ ≥ 4.9
      [fvcore](https://github.com/facebookresearch/fvcore)
      [ioPath](https://github.com/facebookresearch/iopath)
      If CUDA is to be used, use a version which is supported by the corresponding pytorch version and at least version 9.2.
      If CUDA is to be used and you are building from source, the CUB library must be available. We recommend version 1.10.0.
```
</describe>

and pytorch 1.7.1 uses cuda:10.2 or 11.0 

If i use a later version of pytorch say 1.8, I am getting the error 

```
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1 
```
while installing pytorch3d:v0.4.0
